# Generated by Django 2.2 on 2021-01-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_auto_20210118_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
