# Generated by Django 2.2 on 2021-01-23 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('blogapp', '0010_auto_20210122_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AddField(
            model_name='like',
            name='object_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_notifications', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='like',
            name='object_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
