# Generated by Django 2.2 on 2021-01-23 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_auto_20210123_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='object_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_like', to='contenttypes.ContentType'),
        ),
    ]
