# Generated by Django 2.2 on 2021-01-24 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_auto_20210123_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='object_content_type',
            new_name='content_type',
        ),
    ]
